name: absence_manager
description: "Crewmeister absence manager app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/features/absence/data/members.json
    - lib/features/absence/data/absences.json
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
