name: absence_manager
description: "Crewmeister absence manager app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.1
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  hive_flutter: ^1.1.0
  icalendar: ^0.1.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  universal_html: ^2.2.4
  url_launcher: ^6.3.0

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  network_image_mock: ^2.1.1

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vectors/
    - lib/features/absence/data/members.json
    - lib/features/absence/data/absences.json

# Generated by Spider
# For more info on configuration, visit https://birjuvachhani.github.io/spider/grouping/
spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false
  # Generates files with given ignore rules for file.
  ignored_rules:
    - public_member_api_docs
  # Location where all the generated references will be stored
  package: features/core/assets
  groups:
    - path: assets/vectors
      class_name: Vectors
      types: [.svg]
